name: ðŸž Bug Report
description: Report unexpected behavior in Scrapoxy.
labels: ["type: bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file an issue! ðŸ™ We apologize for any inconvenience caused and aim to resolve it promptly.

        Help us help you! We understand your time is valuable, and to expedite a solution, providing detailed information is crucial.

  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: Describe the current behavior you are experiencing.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Describe the behavior you expect to occur.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Provide detailed instructions to reproduce the issue. Be as specific as possible.
      value: |
        1.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Failure Logs
      description: Include relevant log snippets or files here. They will be automatically formatted as code, so no need for backticks.
      render: shell

  - type: input
    id: pm
    attributes:
      label: Scrapoxy Version
      description: Provide the version of Scrapoxy.
    validations:
      required: true

  - type: checkboxes
    id: custom
    attributes:
      label: Custom Version
      description: Is it a modified version of Scrapoxy (fork, custom build, etc.)?
      options:
        - label: 'No'
        - label: 'Yes'

  - type: checkboxes
    id: deployment
    attributes:
      label: Deployment
      description: Select the deployment method you are using.
      options:
        - label: Docker
        - label: Docker Compose
        - label: Kubernetes
        - label: NPM
        - label: Other (Specify in Additional Information)

  - type: checkboxes
    id: os
    attributes:
      label: Operating System
      description: Select your operating system.
      options:
        - label: Linux
        - label: Windows
        - label: macOS
        - label: Other (Specify in Additional Information)

  - type: checkboxes
    id: storage
    attributes:
      label: Storage
      description: Select the storage method used with Scrapoxy.
      options:
        - label: File (default)
        - label: MongoDB & RabbitMQ
        - label: Other (Specify in Additional Information)

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Provide any additional information that may be relevant.

  - type: markdown
    attributes:
      value: |
        > If we cannot reproduce the issue, we may prioritize fixing other reproducible issues. Please complete all sections to the best of your ability.
