export default {
    'order/properties-order': [
        {
            groupName: 'position',
            emptyLineBefore: 'always',
            properties: [
                'display',
                'visibility',
                'position',
                'clear',
                'float',
                'clip',
                'top',
                'bottom',
                'left',
                'right',
                'width',
                'min-width',
                'max-width',
                'height',
                'min-height',
                'max-height',
                'order',
                'z-index',
                'overflow',
                'overflow-x',
                'overflow-y',
            ],
        },
        {
            groupName: 'flex',
            emptyLineBefore: 'always',
            properties: [
                'align-content',
                'align-items',
                'align-self',
                'flex',
                'flex-basis',
                'flex-direction',
                'flex-flow',
                'flex-grow',
                'flex-shrink',
                'flex-wrap',
                'justify-content',
                'order',
            ],
        },
        {
            groupName: 'margin',
            emptyLineBefore: 'always',
            properties: [
                'margin',
                'margin-top',
                'margin-bottom',
                'margin-left',
                'margin-right',
                'padding',
                'padding-top',
                'padding-bottom',
                'padding-left',
                'padding-right',
            ],
        },
        {
            groupName: 'color',
            emptyLineBefore: 'always',
            properties: [
                'background',
                'background-attachment',
                'background-clip',
                'background-image',
                'background-origin',
                'background-position',
                'background-repeat',
                'background-size',
                'border',
                'border-collapse',
                'border-color',
                'border-image',
                'border-image-outset',
                'border-image-repeat',
                'border-image-slice',
                'border-image-source',
                'border-image-width',
                'border-radius',
                'border-spacing',
                'border-style',
                'border-width',
                'border-top',
                'border-top-color',
                'border-top-left-radius',
                'border-top-right-radius',
                'border-top-style',
                'border-top-width',
                'border-bottom',
                'border-bottom-color',
                'border-bottom-left-radius',
                'border-bottom-right-radius',
                'border-bottom-style',
                'border-bottom-width',
                'border-left',
                'border-left-color',
                'border-left-style',
                'border-left-width',
                'border-right',
                'border-right-color',
                'border-right-style',
                'border-right-width',
                'box-shadow',
                'box-sizing',
                'color',
                'opacity',
                'outline',
            ],
        },
        {
            groupName: 'font',
            emptyLineBefore: 'always',
            properties: [
                'direction',
                'font',
                'font-family',
                'font-size',
                'font-style',
                'font-weight',
                'letter-spacing',
                'line-height',
                'text-align',
                'text-decoration',
                'text-decoration-color',
                'text-decoration-line',
                'text-decoration-style',
                'text-indent',
                'text-justify',
                'text-overflow',
                'text-shadow',
                'text-transform',
                'vertical-align',
                'white-space',
                'word-break',
                'word-spacing',
                'word-wrap',
            ],
        },
        {
            groupName: 'list',
            emptyLineBefore: 'always',
            properties: [
                'list-style',
                'list-style-image',
                'list-style-position',
                'list-style-type',
            ],
        },
        {
            groupName: 'animation',
            emptyLineBefore: 'always',
            properties: [
                'animation',
                'animation-delay',
                'animation-direction',
                'animation-duration',
                'animation-fill-mode',
                'animation-iteration-count',
                'animation-name',
                'animation-play-state',
                'animation-timing-function',
                'transform',
                'transform-origin',
                'transform-style',
                'transition',
                'transition-delay',
                'transition-property',
                'transition-timing-function',
            ],
        },
        {
            groupName: 'misc',
            emptyLineBefore: 'always',
            properties: [
                'cursor',
                'outline',
                'outline-color',
                'outline-offset',
                'outline-style',
                'outline-width',
                'quotes',
            ],
        },
    ],
};
